<wsdl:definitions name="INSERT_POS_TRX" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DESARROLLO_17MARZO/CL_DIF_OMS_Demand/INSERT_POS_TRX" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DESARROLLO_17MARZO/CL_DIF_OMS_Demand/INSERT_POS_TRX" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/INSERT_POS_TRX" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="INSERT_POS_TRX_plt">
    <plt:role name="INSERT_POS_TRX_role">
      <plt:portType name="tns:INSERT_POS_TRX_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
     <schema xmlns="http://www.w3.org/2001/XMLSchema">
       <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/INSERT_POS_TRX" schemaLocation="INSERT_POS_TRX_sp.xsd"/>
     </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="INSERT_POS_TRX_ptt">
        <wsdl:operation name="INSERT_POS_TRX">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>