<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DESARROLLO_17MARZO/CL_DIF_OMS_Demand/INSERT_POS_TRX" name="INSERT_POS_TRX-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="INSERT_POS_TRX.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DESARROLLO_17MARZO/CL_DIF_OMS_Demand/INSERT_POS_TRX"/>
    <wsdl:binding name="INSERT_POS_TRX_ptt-binding" type="ins:INSERT_POS_TRX_ptt" xmlns:ins="http://xmlns.oracle.com/pcbpel/adapter/db/DESARROLLO_17MARZO/CL_DIF_OMS_Demand/INSERT_POS_TRX">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="INSERT_POS_TRX">
            <soap:operation soapAction="INSERT_POS_TRX"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>