<wsdl:definitions name="registrarOrdenPedidoLocal" targetNamespace="CVInventarios" xmlns:tns="CVInventarios" xmlns:inp1="CVInventarios" xmlns:inp2="CVInventarios" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="CVInventarios" schemaLocation="../XSD/XSD_RegistrarOrdenPedidoRq.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="CVInventarios" schemaLocation="../XSD/XSD_RegistrarOrdenPedidoRs.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="requestMessage">
    <wsdl:part name="registrarOrdenPedidoRq" element="inp1:registrarOrdenPedidoRq"/>
  </wsdl:message>
  <wsdl:message name="replyMessage">
    <wsdl:part name="registrarOrdenPedidoRs" element="inp1:registrarOrdenPedidoRs"/>
  </wsdl:message>
  <wsdl:portType name="registrarOrdenPedido_ptt">
    <wsdl:operation name="registrarOrdenPedido">
      <wsdl:input message="tns:requestMessage"/>
      <wsdl:output message="tns:replyMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="registrarOrdenPedido_bind" type="tns:registrarOrdenPedido_ptt">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="registrarOrdenPedido">
      <soap:operation style="document" soapAction="registrarOrdenPedido"/>
      <wsdl:input>
        <soap:body use="literal" namespace="http://xmlns.oracle.com/DESARROLLOS_DIFARMA/WSOrdenECommerce/registrarOrdenPedidoLocal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" namespace="http://xmlns.oracle.com/DESARROLLOS_DIFARMA/WSOrdenECommerce/registrarOrdenPedidoLocal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>